CREATE TABLE [CATEGORIAS] (
	ID_CATEGORIA int NOT NULL,
	NOMBRE nvarchar NOT NULL,
  CONSTRAINT [PK_CATEGORIAS] PRIMARY KEY CLUSTERED
  (
  [ID_CATEGORIA] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [DISPOSITIVOS] (
	NUM_SERIE nvarchar NOT NULL,
	ID_CATEGORIA nvarchar NOT NULL,
	MARCA nvarchar NOT NULL,
	MODELO nvarchar NOT NULL,
	ESTADO nvarchar NOT NULL,
	LOCALIZACION nvarchar NOT NULL,
  CONSTRAINT [PK_DISPOSITIVOS] PRIMARY KEY CLUSTERED
  (
  [NUM_SERIE] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [SOLICITUDES] (
	NUM_SERIE nvarchar NOT NULL,
	ID_USUARIO int NOT NULL,
	ESTADO char NOT NULL,
  CONSTRAINT [PK_SOLICITUDES] PRIMARY KEY CLUSTERED
  (
  [NUM_SERIE] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [USUARIOS] (
	ID_USUARIO int NOT NULL,
	CORREO int NOT NULL,
	NOMBRE int NOT NULL,
	PRIMER_APELLIDO int NOT NULL,
	SEGUNDO_APELLIDO int NOT NULL,
	TIPO char NOT NULL,
	CONTRASENIA int NOT NULL,
  CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED
  (
  [ID_USUARIO] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [PANTALLAS] (
	NUM_SERIE nvarchar NOT NULL,
	PULGADAS int(500) NOT NULL,
  CONSTRAINT [PK_PANTALLAS] PRIMARY KEY CLUSTERED
  (
  [NUM_SERIE] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [HW_RED] (
	NUM_SERIE nvarchar NOT NULL,
	NUM_PUERTOS int NOT NULL,
	VELOCIDAD int NOT NULL,
  CONSTRAINT [PK_HW_RED] PRIMARY KEY CLUSTERED
  (
  [NUM_SERIE] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [ORDENADOR] (
	NUM_SERIE nvarchar NOT NULL,
	PROCESADOR nvarchar NOT NULL,
	RAM nvarchar NOT NULL,
	DISCO_PRINCIPAL nvarchar NOT NULL,
	DISCO_SECUNDARIO nvarchar NOT NULL,
  CONSTRAINT [PK_ORDENADOR] PRIMARY KEY CLUSTERED
  (
  [NUM_SERIE] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

ALTER TABLE [DISPOSITIVOS] WITH CHECK ADD CONSTRAINT [DISPOSITIVOS_fk0] FOREIGN KEY ([ID_CATEGORIA]) REFERENCES [CATEGORIAS]([ID_CATEGORIA])
ON UPDATE CASCADE
GO
ALTER TABLE [DISPOSITIVOS] CHECK CONSTRAINT [DISPOSITIVOS_fk0]
GO

ALTER TABLE [SOLICITUDES] WITH CHECK ADD CONSTRAINT [SOLICITUDES_fk0] FOREIGN KEY ([NUM_SERIE]) REFERENCES [DISPOSITIVOS]([NUM_SERIE])
ON UPDATE CASCADE
GO
ALTER TABLE [SOLICITUDES] CHECK CONSTRAINT [SOLICITUDES_fk0]
GO
ALTER TABLE [SOLICITUDES] WITH CHECK ADD CONSTRAINT [SOLICITUDES_fk1] FOREIGN KEY ([ID_USUARIO]) REFERENCES [USUARIOS]([ID_USUARIO])
ON UPDATE CASCADE
GO
ALTER TABLE [SOLICITUDES] CHECK CONSTRAINT [SOLICITUDES_fk1]
GO


ALTER TABLE [PANTALLAS] WITH CHECK ADD CONSTRAINT [PANTALLAS_fk0] FOREIGN KEY ([NUM_SERIE]) REFERENCES [DISPOSITIVOS]([NUM_SERIE])
ON UPDATE CASCADE
GO
ALTER TABLE [PANTALLAS] CHECK CONSTRAINT [PANTALLAS_fk0]
GO

ALTER TABLE [HW_RED] WITH CHECK ADD CONSTRAINT [HW_RED_fk0] FOREIGN KEY ([NUM_SERIE]) REFERENCES [DISPOSITIVOS]([NUM_SERIE])
ON UPDATE CASCADE
GO
ALTER TABLE [HW_RED] CHECK CONSTRAINT [HW_RED_fk0]
GO

ALTER TABLE [ORDENADOR] WITH CHECK ADD CONSTRAINT [ORDENADOR_fk0] FOREIGN KEY ([NUM_SERIE]) REFERENCES [DISPOSITIVOS]([NUM_SERIE])
ON UPDATE CASCADE
GO
ALTER TABLE [ORDENADOR] CHECK CONSTRAINT [ORDENADOR_fk0]
GO

) WITH (IGNORE_DUP_KEY = OFF)

)
GO

ALTER TABLE [EQUIPOS] WITH CHECK ADD CONSTRAINT [EQUIPOS_fk0] FOREIGN KEY ([ID_CATEGORIA]) REFERENCES [CATEGORIAS]([ID_CATEGORIA])
ON UPDATE CASCADE
GO
ALTER TABLE [EQUIPOS] CHECK CONSTRAINT [EQUIPOS_fk0]
GO

ALTER TABLE [SOLICITUDES] WITH CHECK ADD CONSTRAINT [SOLICITUDES_fk0] FOREIGN KEY ([NUM_SERIE]) REFERENCES [EQUIPOS]([NUM_SERIE])
ON UPDATE CASCADE
GO
ALTER TABLE [SOLICITUDES] CHECK CONSTRAINT [SOLICITUDES_fk0]
GO
ALTER TABLE [SOLICITUDES] WITH CHECK ADD CONSTRAINT [SOLICITUDES_fk1] FOREIGN KEY ([ID_USUARIO]) REFERENCES [USUARIOS]([ID_USUARIO])
ON UPDATE CASCADE
GO
ALTER TABLE [SOLICITUDES] CHECK CONSTRAINT [SOLICITUDES_fk1]
GO


ALTER TABLE [PANTALLAS] WITH CHECK ADD CONSTRAINT [PANTALLAS_fk0] FOREIGN KEY ([NUM_SERIE]) REFERENCES [EQUIPOS]([NUM_SERIE])
ON UPDATE CASCADE
GO
ALTER TABLE [PANTALLAS] CHECK CONSTRAINT [PANTALLAS_fk0]
GO

ALTER TABLE [HW_RED] WITH CHECK ADD CONSTRAINT [HW_RED_fk0] FOREIGN KEY ([NUM_SERIE]) REFERENCES [EQUIPOS]([NUM_SERIE])
ON UPDATE CASCADE
GO
ALTER TABLE [HW_RED] CHECK CONSTRAINT [HW_RED_fk0]
GO

ALTER TABLE [ORDENADOR] WITH CHECK ADD CONSTRAINT [ORDENADOR_fk0] FOREIGN KEY ([NUM_SERIE]) REFERENCES [EQUIPOS]([NUM_SERIE])
ON UPDATE CASCADE
GO
ALTER TABLE [ORDENADOR] CHECK CONSTRAINT [ORDENADOR_fk0]
GO


